import Link from 'next/link';
import { ArrowRight, Sparkles, Smartphone, Download, Code2 } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/30">
      {/* Header */}
      <header className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="font-semibold text-lg">SwiftShip</span>
          </div>
          <nav className="flex items-center gap-4">
            <Link
              href="/projects/new"
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
            >
              Start Building
              <ArrowRight className="w-4 h-4" />
            </Link>
          </nav>
        </div>
      </header>

      {/* Hero */}
      <main className="container mx-auto px-4">
        <section className="py-24 text-center">
          <h1 className="text-5xl font-bold tracking-tight mb-6">
            Build iOS Apps with
            <span className="text-primary"> AI</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
            Describe your app in plain English. Watch AI generate a complete SwiftUI app. Export a
            ready-to-compile Xcode project.
          </p>
          <div className="flex items-center justify-center gap-4">
            <Link
              href="/projects/new"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors text-lg"
            >
              <Sparkles className="w-5 h-5" />
              Create New App
            </Link>
          </div>
        </section>

        {/* Features */}
        <section className="py-16 grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
          <FeatureCard
            icon={<Sparkles className="w-6 h-6" />}
            title="AI-Powered Generation"
            description="Describe your app idea and watch AI create a complete component tree with proper iOS patterns."
          />
          <FeatureCard
            icon={<Smartphone className="w-6 h-6" />}
            title="Live Preview"
            description="See your app in a browser-based iOS simulator. Iterate instantly without Xcode."
          />
          <FeatureCard
            icon={<Download className="w-6 h-6" />}
            title="Export to Xcode"
            description="Download a complete Xcode project with pure SwiftUI code. Build and submit to the App Store."
          />
        </section>

        {/* How it works */}
        <section className="py-16 max-w-4xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">How It Works</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <StepCard
              number={1}
              title="Describe Your App"
              description="Tell the AI what you want to build in plain English."
            />
            <StepCard
              number={2}
              title="Iterate & Refine"
              description="Chat with AI to add features, fix layouts, and perfect your design."
            />
            <StepCard
              number={3}
              title="Export & Ship"
              description="Download your Xcode project and submit to the App Store."
            />
          </div>
        </section>

        {/* Code preview */}
        <section className="py-16 max-w-4xl mx-auto">
          <div className="bg-card border rounded-xl p-8">
            <div className="flex items-center gap-2 mb-6">
              <Code2 className="w-5 h-5 text-primary" />
              <span className="font-medium">Generated SwiftUI Code</span>
            </div>
            <pre className="text-sm overflow-x-auto">
              <code className="text-muted-foreground">{`// Generated by SwiftShip

import SwiftUI

struct ContentView: View {
    var body: some View {
        NavigationStack {
            List {
                ForEach(items) { item in
                    Text(item.title)
                }
            }
            .navigationTitle("My App")
        }
    }
}`}</code>
            </pre>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t py-8 mt-16">
        <div className="container mx-auto px-4 text-center text-muted-foreground">
          <p>Built with SwiftShip. Generate native iOS apps with AI.</p>
        </div>
      </footer>
    </div>
  );
}

function FeatureCard({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="p-6 rounded-xl border bg-card hover:shadow-lg transition-shadow">
      <div className="w-12 h-12 rounded-lg bg-primary/10 text-primary flex items-center justify-center mb-4">
        {icon}
      </div>
      <h3 className="font-semibold text-lg mb-2">{title}</h3>
      <p className="text-muted-foreground">{description}</p>
    </div>
  );
}

function StepCard({ number, title, description }: { number: number; title: string; description: string }) {
  return (
    <div className="text-center">
      <div className="w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xl font-bold mx-auto mb-4">
        {number}
      </div>
      <h3 className="font-semibold text-lg mb-2">{title}</h3>
      <p className="text-muted-foreground">{description}</p>
    </div>
  );
}
