/**
 * @swiftship/codegen
 *
 * Swift code generation engine.
 * Converts component trees to native Swift/SwiftUI code.
 */

export * from './ast/types';
export * from './ast/printer';
export * from './generators/primitives';

// Main entry point for code generation
import type { AppDefinition, ComponentNode } from '@swiftship/core';
import type { SwiftNode, ImportDecl, StructDecl, PropertyDecl, ViewBuilderExpr } from './ast/types';
import { printSwift } from './ast/printer';
import { generateText, generateButton, generateImage, generateIcon, generateSpacer, generateDivider } from './generators/primitives';

/**
 * Generator function type.
 */
type ComponentGenerator = (node: ComponentNode) => ViewBuilderExpr;

/**
 * Registry of component generators.
 */
const GENERATORS: Record<string, ComponentGenerator> = {
  text: generateText,
  button: generateButton,
  image: generateImage,
  icon: generateIcon,
  spacer: generateSpacer,
  divider: () => generateDivider(),
  // Add more generators as we build them
};

/**
 * Generate Swift AST for a component node.
 */
export function generateComponentAST(node: ComponentNode): ViewBuilderExpr {
  const generator = GENERATORS[node.type];

  if (!generator) {
    // Fallback: generate a placeholder comment
    return {
      kind: 'view-builder',
      viewName: 'Text',
      arguments: [{ value: { kind: 'string-literal', value: `[Unknown: ${node.type}]` } }],
    };
  }

  const view = generator(node);

  // Recursively generate children if present
  if (node.children && node.children.length > 0) {
    view.trailingClosure = node.children.map(generateComponentAST);
  }

  return view;
}

/**
 * Generate a complete SwiftUI View file.
 */
export function generateViewFile(viewName: string, rootNode: ComponentNode): string {
  const imports: ImportDecl[] = [{ kind: 'import', module: 'SwiftUI' }];

  const bodyProperty: PropertyDecl = {
    kind: 'property',
    name: 'body',
    type: 'some View',
    isComputed: true,
    getter: [generateComponentAST(rootNode)],
  };

  const viewStruct: StructDecl = {
    kind: 'struct',
    name: viewName,
    conformances: ['View'],
    members: [bodyProperty],
  };

  const previewStruct: StructDecl = {
    kind: 'struct',
    name: `${viewName}_Previews`,
    conformances: ['PreviewProvider'],
    members: [
      {
        kind: 'property',
        name: 'previews',
        type: 'some View',
        isComputed: true,
        accessLevel: 'internal',
        getter: [
          {
            kind: 'view-builder',
            viewName: viewName,
          } as ViewBuilderExpr,
        ],
      } as PropertyDecl,
    ],
  };

  const nodes: SwiftNode[] = [...imports, viewStruct, previewStruct];

  // Add header comment
  const header = `// Generated by SwiftShip
// https://swiftship.app
// DO NOT EDIT - Changes will be overwritten

`;

  return header + printSwift(nodes);
}

/**
 * Result of generating an app.
 */
export interface GeneratedApp {
  files: Array<{
    path: string;
    content: string;
  }>;
}

/**
 * Generate all files for an app definition.
 */
export function generateApp(app: AppDefinition): GeneratedApp {
  const files: GeneratedApp['files'] = [];

  // Generate view files for each screen
  for (const screen of app.screens) {
    const viewName = `${pascalCase(screen.name)}View`;
    const content = generateViewFile(viewName, screen.content);
    files.push({
      path: `Sources/Views/${viewName}.swift`,
      content,
    });
  }

  // Generate App entry point
  files.push({
    path: `Sources/${app.config.name}App.swift`,
    content: generateAppFile(app),
  });

  // Generate ContentView (entry view)
  files.push({
    path: 'Sources/ContentView.swift',
    content: generateContentView(app),
  });

  return { files };
}

/**
 * Generate the main App file.
 */
function generateAppFile(app: AppDefinition): string {
  return `// Generated by SwiftShip
// https://swiftship.app

import SwiftUI

@main
struct ${app.config.name}App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
`;
}

/**
 * Generate the ContentView entry point.
 */
function generateContentView(app: AppDefinition): string {
  // If app has tab bar, generate TabView
  if (app.tabBar) {
    const tabs = app.tabBar.tabs
      .map(
        (tab) => `
            ${pascalCase(tab.screen)}View()
                .tabItem {
                    Label("${tab.title}", systemImage: "${tab.icon}")
                }`
      )
      .join('\n');

    return `// Generated by SwiftShip
// https://swiftship.app

import SwiftUI

struct ContentView: View {
    var body: some View {
        TabView {${tabs}
        }
    }
}

#Preview {
    ContentView()
}
`;
  }

  // Otherwise, just show the entry screen
  const entryScreen = app.screens.find((s) => s.id === app.entryScreen);
  const entryViewName = entryScreen ? `${pascalCase(entryScreen.name)}View` : 'Text("No entry screen")';

  return `// Generated by SwiftShip
// https://swiftship.app

import SwiftUI

struct ContentView: View {
    var body: some View {
        ${entryViewName}()
    }
}

#Preview {
    ContentView()
}
`;
}

/**
 * Convert string to PascalCase.
 */
function pascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}
